name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install Prisma CLI
      - name: Install Prisma CLI
        run: npm install -g prisma

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 6️⃣ Generate Prisma Client
      - name: Generate Prisma Client
        run: npm run db:generate

      # 8️⃣ Build the app (Next.js)
      - name: Build the app
        run: npm run build

    
